name: Joseli.to Deploy
on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/15 9-20 * * *'
jobs:
  pt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install PT dependencies
        working-directory: ./pt
        run: yarn install
      - name: Build PT
        working-directory: ./pt
        run: yarn build
      - name: Minify PT
        working-directory: ./pt
        run: yarn minify
      - name: Generate PT Feeds
        working-directory: ./pt
        run: yarn feeds
      - name: Minify PT Feeds
        working-directory: ./pt
        run: yarn minify:feeds
      - name: Move PT to root
        run: ls && mv pt/output/index.html public/pt/index.html
      - name: Move PT Feeds to root
        run: ls && mkdir public/pt/feed && mv -v pt/output/feed/* public/pt/feed/
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
          vercel-args: '--prod'
          working-directory: ./public