name: Joseli.to Deploy
on:
  push:
    branches:
      - main
  schedule:
    - cron: '45 12-23 * * *'
jobs:
  pt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install PT dependencies
        working-directory: ./pt
        run: yarn install
      - name: Build PT
        working-directory: ./pt
        run: yarn build
      - name: Minify PT
        working-directory: ./pt
        run: yarn minify
      - name: Create mobile folder
        working-directory: ./pt
        run: mkdir output/mobile
      - name: Minify PT mobile
        working-directory: ./pt
        run: yarn minify:mobile
      - name: Generate PT Feeds
        working-directory: ./pt
        run: yarn feeds
      - name: Move PT to root
        run: mv pt/output/index.html public/pt/index.html
      - name: Move PT mobile to root
        run: mv pt/output/mobile/index.html public/mobile/pt/index.html
      - name: Move PT Feeds to root
        run: mkdir public/pt/feed && mv -v pt/output/feed/* public/pt/feed/
      - name: Replicate vercel.json
        run: cp public/vercel.json public/mobile/vercel.json
      - name: Replicate assets PT
        run: cp -r public/pt/assets/* public/mobile/pt/assets
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
          vercel-args: '--prod'
          working-directory: ./public
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.MOBILE_PROJECT_ID }}
          vercel-args: '--prod'
          working-directory: ./public/mobile