name: Joseli.to Deploy
on: [push]

jobs:
  pt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
      - name: Install PT dependencies
        working-directory: ./pt
        run: yarn install
      - name: Build PT
        working-directory: ./pt
        run: yarn build
      - name: Minify PT
        working-directory: ./pt
        run: yarn minify
      - name: Move PT to root
        run: ls && mv pt/output/index.html public/pt/index.html
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
          vercel-args: '--prod'
          working-directory: ./public